### ISSUE TITLE
Create Release google calendar

### ISSUE THREAD

**Issue by mikementor** [Leitirion/My_react_playground#24]
1. Create google calendar
2. Link it with ifttt.com with telegram group (DevMates) - so when event starts it sends notification in telegram
3. Create recurring events:
Planning - every Monday (9am, 1 hour)
Daily - every Tuesday, Wednesday,Thursday,Friday (9am 10 minutes)
4. add calendar to the schedule project entrypoint  https://www.notion.so/Project-RPGUIA-5c069879e3c248e5ae875de8fec6141a?p=8d3b5036f44a43b4a14518184e4b8b90&showMoveTo=true  (**Next Events:** )
how:
https://www.notion.so/Embed-Google-Calendar-f1dd42e7071d495ca6764d03c1d2972e

**Comment by Leitirion** [comment]
1. Completed
2. Completed (need test)
3. Completed
4. Completed
