### ISSUE TITLE
List all of the requirements from hh vacancies.

### ISSUE THREAD

**Issue by mikementor** [Leitirion/My_react_playground#25]
Why: to bring into the roadmap features, people ask for on their jobs

**Comment by mikementor** [comment]
Estimates: 2h

**Comment by Leitirion** [comment]
1. ООО Ак Барс Цифровые Технологии 
Козья слобода, Казань, Чистопольская улица, 11

Задачи:

ручное тестирование;
функциональное тестирование веб-приложения и веб-сервисов.
Нам нужен опыт:

создания стратегии/плана тестирования;
тестирования в Agile methodologies, CI, CD;
проведения функционального тестирования;
понимание микросервисной архитектуры
ведения тестовой документации (TestRail);
понимание подходов тестирования frontend, backend и умение применять их;
владение инструментами для получения и анализа log'ов;
знание архитектур клиент-серверных приложений;
умение составлять SQL запросы;
знания стека протоколов TCP/IP.

**Comment by Leitirion** [comment]
2. ГК InnoSTage (ООО Телеком Интеграция) 
Казань

Мы ищем специалистов QA engineer (ручное функциональное тестирование) на проекты в области банковских технологии (ПО, электронные архивы, веб/ мобильные приложения и т.д.,)

Основные требования:

Знание основных этапов тестирования: анализ требований, проектирование и создание тестов, выполнение тестов, анализ результатов тестирования. Понимание задач тестировщика на данных этапах;
Умение считать покрытие функциональности тестовыми сценариями;
Знание тестовой документации: баг-репортов, тест-кейсов, чек-листов и тест-планов;
Знание стадий жизненного цикла ПО;
Знание TCP, HTTP, HTTPS, IPv6.
Знание техник тест-дизайна: Equivalence Partitioning, Boundary Value Analysis, Cause/Effect, Error Guessing. Дополнительно: Decision Table Testing, State-Transition Diagrams, State-Transition Tables, Pairwaise testing;
Работа с требованиями: документирование, процесс управления, декомпозиция, тестирование;
Работа с баг трекерами;
Знание принципов работы с одним из инструментов: SoapUI, Postman, Fiddler;
Понимание REST, SOAP.

**Comment by Leitirion** [comment]
3. Миррико, Группа Компаний 
Обязанности:
Проведение различных типов тестирования функционала.
Анализ бизнес-требований и определение приемочных критериев.
Планирование тестирования, разработка тест-стратегии, тест-планов, тест-сценариев.
Регистрация и мониторинг обнаруженных дефектов.
Взаимодействие с разработчиками, аналитиками и менеджером продукта
Проверка требований к продукту, оценка рисков.
Планирование идей по улучшению качества продукта.
Требования:
Высшее техническое образование (физика, математика, разработка ПО, АСУ и АСУТП, техника и технология).
Опыт работы более 1 года.
Знание и использование систем управления тестированием, отслеживания ошибок.
Знание и понимание основ архитектуры информационных систем и работы современных веб-приложений, понимание принципов работы сетей, протоколов TCP/IP, HTTP и т.п.
Понимание методологий тестирования программного обеспечения и процессов разработки, представления о разработке тестов, тест-кейсов и тестовых планов.
Умение анализировать требования и составлять необходимые сценарии тестирования.
Грамотная устная и письменная речь, умение документировать свои действия и описывать найденные ошибки.
Знание английского языка (pre-intermediate): чтение тематической литературы, ресурсов.
Владение офисными и графическими редакторами, инструментами нагрузочного тестирования.

**Comment by Leitirion** [comment]
4. ООО Бизапс 
Казань

Наши требования:

опыт работы тестировщиком от 1 года
знание методологий и принципов тестирования
умение составлять тестовую документацию
умение писать SQL запросы (знать отличие CROSS JOIN от FULL JOIN)
знание английского языка на уровне переписки
Чем вам предстоит заниматься:

ручное тестирование: составление тест-планов, тест-кейсов, отчетов
тестирование ПО на соответствие техническим требованиям и внутренним регламентам
анализ результатов тестирования и предоставление отчетов по тестированию

**Comment by Leitirion** [comment]
5. ООО Data Armor 
Казань, Петербургская улица, 50к8

Обязанности:

Ручное тестирование ПО, разрабатываемого компанией;
Разработка и сопровождение системы автоматизированного тестирования;
Проверка документации.
Требования:

Знание основ программирования;
Знание языка запросов SQL, опыт работы с базами данных;
Аналитический склад ума, внимательность к деталям;
Свободное чтение англоязычной технической литературы.
Приветствуется:

Опыт автоматизации тестирования;
Опыт работы с трекерами задач;
Умение работать с системами контроля версий;
Знание одного или нескольких языков программирования;
Опыт написания тест-кейсов, составления тест-планов, подготовка чек-листов.

**Comment by Leitirion** [comment]
6. ООО Управление информационными проектами 
Казань, ул. Петербургская 52, IT-парк

### Мы ищем тестировщика, способного быстро изучить работу системы и выполнить задачи:

Написание тест-кейсов;
Выполнение ручного функционального тестирования ПО;
Поиск и анализ дефектов‚ занесение в систему багтрекинга;
Анализ результатов тестирования и предоставление отчетов по тестированию.
### Требования:

Знание основных понятий и видов тестирования ПО на базовом уровне;
Уверенный пользователь ПК, интерес к сфере ИТ;
Внимательность‚ аккуратность‚ исполнительность, усидчивость;
Логическое мышление, аналитический склад ума;
Желательно высшее образование (также рассматриваются студенты последних курсов, заочники и вечерники).
